# Generated by Django 2.1 on 2018-08-26 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineAccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_url', models.URLField(blank=True, null=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=128)),
                ('account_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('account_id', models.CharField(blank=True, max_length=128, null=True)),
                ('account_passwd', models.CharField(blank=True, max_length=128, null=True)),
                ('account_passwd_chgDate', models.DateTimeField(blank=True, null=True)),
                ('account_subscription_type', models.CharField(blank=True, max_length=128, null=True)),
                ('account_subscription_payDate', models.DateTimeField(blank=True, null=True)),
                ('account_2fa', models.CharField(blank=True, max_length=255, null=True)),
                ('account_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_tool.OnlineAccountModel')),
            ],
        ),
    ]
