# Generated by Django 2.1 on 2018-08-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineaccountmodel',
            name='account_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_tool.OnlineAccountModel'),
        ),
    ]
