# Generated by Django 2.1 on 2018-08-29 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_tool', '0002_auto_20180828_0934'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onlineaccountmodel',
            unique_together={('account_url', 'account_name')},
        ),
    ]
