# Generated by Django 2.1 on 2018-09-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_tool', '0003_auto_20180829_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineaccountmodel',
            name='account_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
